---

- hosts: all
  become: true
  pre_tasks:
  
  - name: install updates(CentOs)
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS" 

  - name: install update(ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"


- hosts: web_servers
  become: true
  tasks: 


  - name: install the apache2 and php for Ubuntu servers
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"     


  - name: install apache and php for centos servers
    dnf: 
      name:
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"


- hosts: db_servers
  become: true
  tasks:

  - name: install Mariadb package (CentOS)
    dnf: 
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"

  - name: install Mariadb package (Ubuntu)
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:
  
  - name: install samba package
    package:
      name: samba
      state: latest 
